CC := gcc
#CC := clang 
#CFLAGS := -O -pthread -D_POSIX_C_SOURCE=200112 -static -integrated-as -msoft-float
CFLAGS := -O3 -pthread -D_POSIX_C_SOURCE=200112
CFLAGS := -g3 -pthread -D_POSIX_C_SOURCE=200112
#CFLAGS := $(CFLAGS) -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
#CFLAGS := $(CFLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels
LDFLAGS := -lm
#LDFLAGS := -lm -static

#BASEDIR := $(HOME)/splash2/codes
BASEDIR := /home/zhy/work/test/splash2-master/codes
MACROS := $(BASEDIR)/null_macros/c.m4.null.POSIX_BARRIER
M4 := m4 -s -Ulen -Uindex

x = *

$(TARGET): $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) -o $(TARGET) $(LDFLAGS)

clean:
	rm -rf *.C *.H *.o $(TARGET)

.SUFFIXES:
.SUFFIXES:	.o .c .h


.c.o:
	$(CC) -c $(CFLAGS) $*.c
