TARGET = programme
OBJS = BullMoose_4.o jacobcalc.o laplacalc.o main.o multi.o slave1.o slave2.o

include ../../../Makefile.config

decs.h: decs.h
jacobcalc.c: decs.h
main.c: decs.h
slave1.c: decs.h
laplacalc.c: decs.h
multi.c : decs.h
slave2.c: decs.h

BullMoose_4.c: BullMoose_4.h